```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r,warning=FALSE,message=FALSE, include=FALSE}
library(data.table)
library(tidyverse)
library(rmarkdown)
library(ggplot2)
library(plyr)
library(lsmeans)
library(multcompView)
library(lmtest)
library(nortest)
library(MASS)
library(olsrr)
library(nortest)
library(lsmeans)
library(car)
library(multcompView)
library(lme4)
library(lmerTest)
library(text2vec)
library(pdist)
library(olsrr)
library(MASS)
library(dplyr)
library(tibble)
library(jmuOutlier)
library(Epi)
library(geosphere)
library(bit64)
options(scipen = 999)
```


```{r}
attach(diamonds)
```
# Analysis  


```{r}
diamonds<-diamonds[complete.cases(diamonds), ]

x=diamonds$x
y=diamonds$y
z=diamonds$z
carat=diamonds$carat
depth=diamonds$depth
tabl=diamonds$table
price=diamonds$price

```

Price and x
```{r}
c=cor(price,x,method = "pearson")
num_perm<-1000
T_perm<-numeric(num_perm)
for(i in 1:num_perm){
  x_tmp<-sample(x) # replace=F, size=length(BMI) by default
  y_tmp<-sample(price)
  T_perm[i]<-cor(x_tmp,y_tmp)
}

hist(T_perm, xlim=c(-1,1))
abline(v=c, col="red", lwd=3)
mean(T_perm>=c)
```

price and y
```{r}
c=cor(price,y,method = "pearson")
num_perm<-1000
T_perm<-numeric(num_perm)
for(i in 1:num_perm){
  x_tmp<-sample(y)
  y_tmp<-sample(price)
  T_perm[i]<-cor(x_tmp,y_tmp)
}

hist(T_perm, xlim=c(-1,1))
abline(v=c, col="red", lwd=3)
mean(T_perm>=c)
```




price and z
```{r}
c=cor(price,z,method = "pearson")
num_perm<-1000
T_perm<-numeric(num_perm)
for(i in 1:num_perm){
  x_tmp<-sample(z) # replace=F, size=length(BMI) by default
  y_tmp<-sample(price)
  T_perm[i]<-cor(x_tmp,y_tmp)
}

hist(T_perm, xlim=c(-1,1))
abline(v=c, col="red", lwd=3)
mean(T_perm>=c)
```

price and carat
```{r}
c=cor(price,carat,method = "pearson")
num_perm<-1000
T_perm<-numeric(num_perm)
for(i in 1:num_perm){
  x_tmp<-sample(carat) # replace=F, size=length(BMI) by default
  y_tmp<-sample(price)
  T_perm[i]<-cor(x_tmp,y_tmp)
}

hist(T_perm, xlim=c(-1,1))
abline(v=c, col="red", lwd=3)
mean(T_perm>=c)
```




price and depth
```{r}
c=cor(price,depth,method = "pearson")
num_perm<-1000
T_perm<-numeric(num_perm)
for(i in 1:num_perm){
  x_tmp<-sample(depth) # replace=F, size=length(BMI) by default
  y_tmp<-sample(price)
  T_perm[i]<-cor(x_tmp,y_tmp)
}

hist(T_perm, xlim=c(-1,1))
abline(v=c, col="red", lwd=3)
mean(T_perm>=c)
```


price and table
```{r}
c=cor(price,table,method = "pearson")
num_perm<-1000
T_perm<-numeric(num_perm)
for(i in 1:num_perm){
  x_tmp<-sample(table) # replace=F, size=length(BMI) by default
  y_tmp<-sample(price)
  T_perm[i]<-cor(x_tmp,y_tmp)
}

hist(T_perm, xlim=c(-1,1))
abline(v=c, col="red", lwd=3)
mean(T_perm>=c)
```

# Results  
We have very strong evidence to suggest that there is a significant correlation between the prices of diamonds and length, width, depth, table and carat. However, we do not have evidence to suggest any correlation between prices of diamonds and its depth percentage. 